#!/bin/bash

### Housekeeping
exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x


### Symlink dotfiles
ln -sf $(pwd)/home/.* $HOME/


### Neovim
if [[ ! -z "$CODESPACES" ]]; then
  # Install Neovim
  apt-get install -y fzf libfuse2
  curl -L -o $HOME/bin/nvim https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage
  chmod a+x $HOME/bin/nvim
fi

mkdir -p $HOME/.config
ln -sf ../nvim $HOME/.config/nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
vim +PlugInstall +qall


### ZSH
ln -sf $(pwd)/zsh/*.zsh $HOME/.oh-my-zsh/custom
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi
