#!/bin/bash

### Housekeeping
exec > >(tee -i $HOME/dotfiles_install.log)
exec 2>&1
set -x


### Symlink dotfiles
ln -sf $(pwd)/home/.* $HOME/


### Neovim
if [[ ! -z "$CODESPACES" ]]; then
  # Install Neovim
  apt-get install -y fzf libfuse2 ruby-dev
  mkdir -p $HOME/bin
  curl -L -o $HOME/bin/nvim https://github.com/neovim/neovim/releases/download/v0.4.4/nvim.appimage
  chmod a+x $HOME/bin/nvim
  gem install neovim
  pip3 install --user pynvim

  curl -L https://github.com/sharkdp/bat/releases/download/v0.18.2/bat-v0.18.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz -C $HOME
  cp $HOME/bat-v0.18.2-x86_64-unknown-linux-gnu/bat $HOME/bin/.
  rm -rf $HOME/bat-v0.18.2-x86_64-unknown-linux-gnu
fi

mkdir -p $HOME/.config
ln -sf $(pwd)/nvim $HOME/.config/nvim
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
$HOME/bin/nvim +PlugInstall +qall


### ZSH
if [[ -d $HOME/.oh-my-zsh ]]; then
  ln -sf $(pwd)/zsh/*.zsh $HOME/.oh-my-zsh/custom

  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

  if ! grep -q "root.*/bin/zsh" /etc/passwd
  then
    chsh -s /bin/zsh root
  fi
fi
